//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosMedicamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consulta()
        {
            this.ConsultaMedicamento = new HashSet<ConsultaMedicamento>();
        }
    
        public int IIDCONSULTA { get; set; }
        public Nullable<int> IIDPACIENTE { get; set; }
        public Nullable<decimal> PESO { get; set; }
        public Nullable<decimal> ESTATURA { get; set; }
        public string EXAMENFISICO { get; set; }
        public string EXAMENLABORATORIO { get; set; }
        public string DIAGNOSTICO { get; set; }
        public Nullable<System.DateTime> FECHACITA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultaMedicamento> ConsultaMedicamento { get; set; }
    }
}
